version: "3.6"

volumes:
  mysql:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  mysql:
    image: mysql:5.7 # Upgrade to 8.x once I get this config work
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
